# TODO: segregate containers in diferent networks
name: transcendence

services:

  db:
    image: postgres:latest
    container_name: tr_db
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data:rwx
    ports:
      - "5432:5432"
    env_file:
      - .env
      # TODO:: add a healthcheck
      # healthcheck:
      #   test: [ "CMD-SHELL", "pg_isready -U $${DATABASE_USER}" ]
      #   interval: 1m30s
      #   timeout: 30s
      #   retries: 5
      #   start_period: 30s

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: always
    volumes:
      - media-data:/app/ft_transcendence/media:rw
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: tr_redis
    restart: always
    volumes:
      - redis-data:/data:rw
    ports:
      - "6379:6379"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - prometheus-data:/prometheus:rw
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    # Take this off when the app is in the docker network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    depends_on:
      - db
      - redis

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/:ro
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    env_file:
      - .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
    depends_on:
      - django

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    env_file:
      - .env
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    env_file:
      - .env
    depends_on:
      - elasticsearch

volumes:
  media-data: {}
  pg-data: {}
  redis-data: {}
  grafana-data: {}
  prometheus-data: {}
  elasticsearch-data: {}
