# TODO: segregate containers in diferent networks
name: transcendence

services:

  db:
    container_name: tr_db
    image: postgres:latest
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data:rwx
    networks:
      - data-layer-network
    expose:
      - "5432"
    env_file:
      - .env
      # TODO:: add a healthcheck
      # healthcheck:
      #   test: [ "CMD-SHELL", "pg_isready -U $${DATABASE_USER}" ]
      #   interval: 1m30s
      #   timeout: 30s
      #   retries: 5
      #   start_period: 30s

  redis:
    container_name: tr_redis
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data:rw
    networks:
      - data-layer-network
    expose:
      - "6379"
    depends_on:
      - db

  django-worker:
    container_name: django-worker
    build:
      context: .
      dockerfile: ./docker/django-worker/Dockerfile
    restart: always
    networks:
      - data-layer-network
    expose:
      - "6379"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: always
    volumes:
      - media-files:/app/ft_transcendence/media:rw
    networks:
      - data-layer-network
      - metrics-scrape-network
      - logs-scrape-network
      - serve-network
    # TODO: Take off the ports directive
    ports:
      - "8000:8000"
    expose:
      - "8000" # so nginx can ping it
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - django-worker

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - prometheus-data:/prometheus:rw
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    networks:
      - metrics-scrape-network
      - metrics-display-network
    expose:
      - "9090" # redundancy for documentation
    ports:
      - "9090:9090"
    depends_on:
      - db
      - redis

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/:ro
    networks:
      - metrics-display-network
    expose:
      - "3000" # redundancy for documentation
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - prometheus

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    restart: always
    env_file:
      - .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw
    networks:
      - logs-display-network
    expose:
      - "9200" # redundancy for documentation
    ports:
      - "9200:9200"
    depends_on:
      - django

  initializer:
    container_name: initializer
    build:
      context: .
      dockerfile: ./docker/initializer/Dockerfile
    restart: on-failure
    volumes:
      - static-files:/var/www/django/static/:rw
      - media-files:/var/www/django/media/:rw
    networks:
      - logs-display-network # pra pingar o elastic
      - data-layer-network # pra pingar o django
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - django

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - logs-scrape-network
      - logs-display-network
    expose:
      - "5044" # a input port que o django vai dar push nos logs
      - "9600" # redundancy for documentation
    ports:
      - "9600:9600" # healthcheck port
    env_file:
      - .env
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    networks:
      - logs-display-network
    expose:
      - "5601" # redundancy for documentation
    ports:
      - "5601:5601"
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - logstash

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    networks:
      - serve-network
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static-files:/var/www/django/static/:ro
      - media-files:/var/www/django/media/:ro
    env_file:
      - .env
    depends_on:
      - django
      - django-worker
      - initializer

volumes:
  pg-data: {}
  redis-data: {}
  grafana-data: {}
  prometheus-data: {}
  elasticsearch-data: {}
  static-files: {}
  media-files: {}

networks:
  metrics-scrape-network: {}
  metrics-display-network: {}
  data-layer-network: {}
  logs-display-network: {}
  logs-scrape-network: {}
  serve-network: {}
