name: transcendence

services:
  db:
    image: postgres:latest
    container_name: tr_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data:rwx
    ports:
      - "5432:5432"
    env_file:
      - .env
      # TODO:: add a healthcheck
      # healthcheck:
      #   test: [ "CMD-SHELL", "pg_isready -U $${DATABASE_USER}" ]
      #   interval: 1m30s
      #   timeout: 30s
      #   retries: 5
      #   start_period: 30s

  redis:
    image: redis:latest
    container_name: tr_redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - db

volumes:
  pg_data:
