# Generated by Django 5.1.2 on 2024-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0002_truser_updated_at_blockedusers_friendrequest_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="truser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="user/assets/foto-perfil.png",
                help_text="Foto de perfil do usuário",
                null=True,
                upload_to="static/assets/profile",
            ),
        ),
    ]
