# Generated by Django 5.1.2 on 2024-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_alter_truser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="assets/foto-perfil.png",
                help_text="Foto de perfil do usuário",
                null=True,
                upload_to="assets/profile",
            ),
        ),
    ]
