# Generated by Django 5.1.2 on 2025-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_alter_truser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="truser",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
