worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include         mime.types;
    default_type    application/octet-stream;
    error_log       /dev/stdout debug;
    access_log      /dev/stdout combined;

    # SSL Configuration
    ssl_certificate         /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key     /etc/nginx/ssl/private.key;
    ssl_protocols           TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers             AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
    # botei pq eles colocaram
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    # Redirect HTTP to HTTPS
    server {
        listen      80;
        server_name _;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen      443 ssl;
        server_name _;

        # HTTP Proxying (for regular Django app traffic)
        location / {
            proxy_pass          http://django:8000;  # Proxy HTTP traffic to Django (or Daphne)
            proxy_set_header    Host $host;
            proxy_set_header    X-Real-IP $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;
        }

        # WebSocket Proxying
        location /ws/ {
            proxy_pass          http://django:8000;  # Proxy WebSocket traffic to Django (or Daphne)
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection 'upgrade';
            proxy_set_header    Host $host;
            proxy_cache_bypass  $http_upgrade;
        }

        # Serve static files volume
        location /static/ {
            alias /var/www/django/static/;  # Adjust to your STATIC_ROOT path
            expires 30d;
        }

        # serve media files volume
        location /media/ {
            alias /var/www/django/media/;  # Adjust to your MEDIA_ROOT path
            expires 30d;
        }

        location /grafana/ {
            proxy_pass          http://grafana:3000/;
            proxy_set_header    HOST $host;
            proxy_set_header    X-Real-Ip $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;
        }

        location /kibana/ {
            proxy_pass          http://kibana:5601/;
            proxy_set_header    HOST $host;
            proxy_set_header    X-Real-Ip $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;
            # those two are because of this:
            # https://www.nathanhunstad.com/blog/2023/05/how-to-configure-kibana-behind-an-nginx-proxy/
            proxy_set_header    Authorization $http_authorization;
            proxy_pass_header   Authorization;
        }
    }
}
