# Generated by Django 5.1.2 on 2024-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pongroom",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
