# Generated by Django 5.1.2 on 2024-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0002_alter_pongroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pongroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("online", "Online"),
                    ("tournament", "Tournament"),
                ],
                default="local",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
