# Generated by Django 5.1.2 on 2024-11-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0003_pongroom_room_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pongroom",
            old_name="room_type",
            new_name="game_mode",
        ),
    ]
