# Generated by Django 5.1.2 on 2024-11-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0005_match_usermatchstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
