# Generated by Django 5.1.2 on 2024-11-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0006_match_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="active",
        ),
        migrations.AddField(
            model_name="match",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
