# Generated by Django 5.1.2 on 2024-12-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0007_remove_match_active_match_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="pongroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
