# Generated by Django 5.1.2 on 2024-12-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0009_tournament_tournamentparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="pongroom",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="pong.tournament",
            ),
        ),
    ]
