# Generated by Django 5.1.2 on 2024-12-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pong", "0011_alter_match_player1_alter_match_player2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserMatchStats",
        ),
    ]
