input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  # Customize log processing here
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "senha123"
    index => "django-logs"
    ssl_enabled => "false"
  }
  stdout { codec => rubydebug }
}
